# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: acunetix360@1
  inputs:
    apiConnection: 'acx1'
    scanTypes: '1'
    scanWebSites: 'db5047cc-7166-444a-919f-adc6044605be'
    hasReport: true
    reportType: 'ScanDetail'
